### ISSUE TITLE
want to add

### ISSUE THREAD

**Issue by deyonlk** [MarcAnt01/Fluent-Screen-Recorder#139] opened 2022-10-03 13:42 UTC
i started the screen recording with fluent screen Recorder but no option to the pause recording

**Comment by MarcAnt01** [comment] 2022-10-04 10:39
Hello, thanks for your feature request. There's already another issue asking to implement this feature

**Comment by MarcAnt01** [comment] 2022-10-04 10:39
Duplicate of https://github.com/MarcAnt01/Fluent-Screen-Recorder/issues/36

**Closed by MarcAnt01** 2022-10-04 10:39 UTC
