### ISSUE TITLE
Recorder crashes when closed the recording window

### ISSUE THREAD

**Issue by Chaniru22** [MarcAnt01/Fluent-Screen-Recorder#69] opened 2021-09-07 13:41 UTC
When I start a record a window it records fine but if I close the window before stop the recording the app freezes and closes

**Comment by MarcAnt01** [comment] 2021-09-10 12:30
It looks like the problem is internal audio recording not stopping, when closing the window. For the moment I found a patch, so that if you close the window the app won't crash, but simply the video recording won't include audio

**Closed by MarcAnt01** 2021-09-10 12:30 UTC
Labels: bug
